### ISSUE TITLE
发送成功未收到消息

### ISSUE THREAD

**Issue by 757350134** [aLiang-xyl/integration-mqtt#1]
localhost:8081/sendMessage?topic="topic1" 我是这样请求的
然而未在Mqtt2MessageHandler中收到消息，请问一下是什么问题？

**Comment by aLiang-xyl** [comment]
可否把代码发我看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wxp"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 上午8:52
收件人:&nbsp;"aLiang-xyl/integration-mqtt"<integration-mqtt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aLiang-xyl/integration-mqtt] 发送成功未收到消息 (#1)





 
localhost:8081/sendMessage?topic="topic1" 我是这样请求的
 然而未在Mqtt2MessageHandler中收到消息，请问一下是什么问题？

**Comment by aLiang-xyl** [comment]
localhost:8081/sendMessage?topic="topic1" 默认是发送至chanel1上，也就是MqttMessageHandler来接收




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wxp"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 上午8:52
收件人:&nbsp;"aLiang-xyl/integration-mqtt"<integration-mqtt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aLiang-xyl/integration-mqtt] 发送成功未收到消息 (#1)





 
localhost:8081/sendMessage?topic="topic1" 我是这样请求的
 然而未在Mqtt2MessageHandler中收到消息，请问一下是什么问题？

**Comment by aLiang-xyl** [comment]
localhost:8081/sendMessage?topic="topic1"请求参数有错误，正确的请求如：localhost:8081/sendMessage?topic=topic1
参数不要加引号


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wxp"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 上午8:52
收件人:&nbsp;"aLiang-xyl/integration-mqtt"<integration-mqtt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aLiang-xyl/integration-mqtt] 发送成功未收到消息 (#1)





 
localhost:8081/sendMessage?topic="topic1" 我是这样请求的
 然而未在Mqtt2MessageHandler中收到消息，请问一下是什么问题？

**Comment by 757350134** [comment]
真的是双引号的问题，感谢！
