### ISSUE TITLE
mqtt设备上线及下线

### ISSUE THREAD

**Issue by 757350134** [aLiang-xyl/integration-mqtt#2]
请问一下mqtt客户端上线怎么判断，mqtt设备下线遗嘱的功能这些能否开源一下

**Comment by aLiang-xyl** [comment]
mqtt客户端是否在线，可调用mqtt的api来确认状态，参见文档：https://docs.emqx.io/broker/latest/cn/advanced/http-api.html#endpoint-clients
api中支持分页获取客户端信息，或者根据clientid查询客户端信息









遗嘱消息是在建立连接的时候设置遗嘱主题、消息内容、qos以及是否保留消息参数：见下图







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aLiang-xyl/integration-mqtt"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午5:29
收件人:&nbsp;"aLiang-xyl/integration-mqtt"<integration-mqtt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aLiang-xyl/integration-mqtt] mqtt设备上线及下线 (#2)





 
请问一下mqtt客户端上线怎么判断，mqtt设备下线遗嘱的功能这些能否开源一下

**Comment by aLiang-xyl** [comment]
抱歉，github不支持图片，再回复一次
mqtt客户端是否在线，可调用mqtt的api来确认状态，参见文档：https://docs.emqx.io/broker/latest/cn/advanced/http-api.html#endpoint-clients
api中支持分页获取客户端信息，或者根据clientid查询客户端信息，打开链接参照文档即可。



遗嘱消息是在建立连接的时候设置遗嘱主题、消息内容、qos以及是否保留消息参数，更改MqttAutoConfiguration类中的方法：
添加：options.setWill(topic, payload, qos, retained);


/**
	 * mqtt工厂
	 *&nbsp;
	 * @param vo
	 * @return
	 */
	private MqttPahoClientFactory mqttClientFactory(Config config) {
		DefaultMqttPahoClientFactory factory = new DefaultMqttPahoClientFactory();
		MqttConnectOptions options = new MqttConnectOptions();


		options.setServerURIs(config.getUrl());
		options.setCleanSession(true);
		options.setKeepAliveInterval(config.getKepAliveInterval());
		options.setPassword(config.getPassword().toCharArray());
		options.setUserName(config.getUsername());
		options.setConnectionTimeout(config.getTimeout());
		options.setWill(topic, payload, qos, retained);


		factory.setConnectionOptions(options);
		return factory;
	}



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aLiang-xyl/integration-mqtt"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午5:29
收件人:&nbsp;"aLiang-xyl/integration-mqtt"<integration-mqtt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aLiang-xyl/integration-mqtt] mqtt设备上线及下线 (#2)





 
请问一下mqtt客户端上线怎么判断，mqtt设备下线遗嘱的功能这些能否开源一下

**Comment by aLiang-xyl** [comment]
遗嘱消息功能已添加

**Comment by aLiang-xyl** [comment]
客户端上下线事件
$SYS 主题前缀: $SYS/brokers/${node}/clients/

主题 (Topic)	说明
${clientid}/connected	上线事件。当任意客户端上线时，EMQ X 就会发布该主题的消息
${clientid}/disconnected	下线事件。当任意客户端下线时，EMQ X 就会发布该主题的消息
connected 事件消息的 Payload 解析成 JSON 格式如下:

{
    "username":"undefined",
    "ts":1582687922392,
    "sockport":1883,
    "proto_ver":5,
    "proto_name":"MQTT",
    "keepalive":300,
    "ipaddress":"127.0.0.1",
    "expiry_interval":0,
    "connected_at":1582687922,
    "connack":0,
    "clientid":"emqtt-8348fe27a87976ad4db3",
    "clean_start":true
}
disconnected 事件消息的 Payload 解析成 JSON 格式如下:

{
    "username":"undefined",
    "ts":1582688032203,
    "reason":"tcp_closed",
    "disconnected_at":1582688032,
    "clientid":"emqtt-8348fe27a87976ad4db3"
