### ISSUE TITLE
订阅消息

### ISSUE THREAD

**Issue by Lily369** [aLiang-xyl/integration-mqtt#4]
实现了MessageHandler还是无法接受到订阅的消息，通道配置正确了，配置文件里也配置了订阅的topic，这是怎么回事？大佬

**Comment by aLiang-xyl** [comment]
springboot用的哪个版本？

**Comment by Lily369** [comment]
用的1.5.3然后使用2.1.9，现在用的2.2.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aLiang-xyl"<notifications@github.com&gt;; 
发送时间: 2020年9月6日(星期天) 晚上7:44
收件人: "aLiang-xyl/integration-mqtt"<integration-mqtt@noreply.github.com&gt;; 
抄送: "Lily."<1174685710@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aLiang-xyl/integration-mqtt] 订阅消息 (#4)





 
springboot用的哪个版本？

**Comment by aLiang-xyl** [comment]
qq1481648291
