### ISSUE TITLE
新增channel问题

### ISSUE THREAD

**Issue by tianbowen14300** [aLiang-xyl/integration-mqtt#6]
新增了channel3 yml中新增了  也新增了channel3对印的MessageHandler 但是使用时就报未查询到相应通道channel3的handler 请问博主是什么问题呢

**Comment by tianbowen14300** [comment]
博主 上面这个问题解决了 然后想问下该项目maven打包问题 要针对那个文件进行打包呢

**Comment by aLiang-xyl** [comment]
现在的代码结构需要在根节点下打包，也就是在integration-mqtt这一层打包

**Comment by tianbowen14300** [comment]
我在根目录的pom文件打包 打出了两个jar包  一个demo的 一个starter的

**Comment by tianbowen14300** [comment]
我在根目录的pom文件打包 打出了两个jar包  一个demo的 一个starter的

**Comment by tianbowen14300** [comment]
启动jar包都报jar中没有主清单属性 我查了一下都说是pom文件没有配置spring-boot-maven-plugin 我在根目录pom文件加上该配置后还是不行

> 现在的代码结构需要在根节点下打包，也就是在integration-mqtt这一层打包

**Comment by aLiang-xyl** [comment]
打包应该是不会有问题的，而且我也曾正常推送只maven中央仓库。直接使用命令行运行： mvn clean package -Dmaven.test.skip=true 进行打包试试

**Comment by tianbowen14300** [comment]
> 

试了下 还是打出了demo 和 starter两个jar包

**Comment by tianbowen14300** [comment]
> 打包应该是不会有问题的，而且我也曾正常推送只maven中央仓库。直接使用命令行运行： mvn clean package -Dmaven.test.skip=true 进行打包试试

java -jar 后报的时=是integration-mqtt-demo-0.0.3-SNAPSHOT.jar中没有主清单属性

**Comment by aLiang-xyl** [comment]
在demo的pom中添加：
<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>2.8.2</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
			<resource>
				<directory>src/main/java</directory>
				<filtering>false</filtering>
				<includes>
					<include>**/xml/*.xml</include>
				</includes>
			</resource>
		</resources>
	</build>

**Comment by aLiang-xyl** [comment]
在demo中添加：

> `<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>2.8.2</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
			<resource>
				<directory>src/main/java</directory>
				<filtering>false</filtering>
				<includes>
					<include>**/xml/*.xml</include>
				</includes>
			</resource>
		</resources>
	</build>`

**Comment by aLiang-xyl** [comment]
demo的pom中添加上面的build配置，打包后运行demo的jar

**Comment by tianbowen14300** [comment]
> demo的pom中添加上面的build配置，打包后运行demo的jar

可以了博主 按照你这个配置打包后运行demo可以运行了 请问是之前是什么问题呢

**Comment by aLiang-xyl** [comment]
之前打的包不是一个可以直接运行的jar包
