### ISSUE TITLE
发送器经常会发送重复消息,接收器也经常会收到重复的消息,是什么原因

### ISSUE THREAD

**Issue by skay0424** [aLiang-xyl/integration-mqtt#7]

**Comment by aLiang-xyl** [comment]
如果经常受到重复消息，两种可能
1.每次启动的时候收到重复消息，如果是这样的话，可能是打开了保留消息开关，清除保留消息方法：关闭保留消息（设置为false），并向主题上发送一个空字符串消息
2.程序运行过程中收到重复消息，更改qos为2，如果是分布式多个程序同时消费一个主题，则需要使用队列模式或共享模式来消费主题
