### ISSUE TITLE
MQTT(32202): 正在发布过多的消息

### ISSUE THREAD

**Issue by vipMhr20150820** [aLiang-xyl/integration-mqtt#9]
从websocket中接收消息，通过MqttUtils.sendMessage方法,运行段时间后，报错spring-integration优化MQTT(32202)异常，网络上搜索了很多方法，都需要设置maxInflight，咱们这个项目怎么配置

**Comment by tianbowen14300** [comment]
同样遇到了这个问题 请问已解决了吗

**Comment by vipMhr20150820** [comment]
> 同样遇到了这个问题 请问已解决了吗

还没有得到开源作者的答复，目前使用线程池进行消息转发，未进行长时间运行测试

**Comment by aLiang-xyl** [comment]
请看最新的版本，已经加上了相应的配置

**Comment by tianbowen14300** [comment]
> 请看最新的版本，已经加上了相应的配置

对应修复是加上了max-inflight这个配置项来解决吗

**Comment by aLiang-xyl** [comment]
是的

**Comment by tianbowen14300** [comment]
> 是的

我尝试过在代码里增大这个数来避免这个错误 但是是没有效果的

**Comment by aLiang-xyl** [comment]
有详细的报错信息吗

**Comment by tianbowen14300** [comment]
就是MQTT(32202): 正在发布过多的消息 这个错误

**Comment by tianbowen14300** [comment]
> > 同样遇到了这个问题 请问已解决了吗
> 
> 还没有得到开源作者的答复，目前使用线程池进行消息转发，未进行长时间运行测试

请问有帖子能分享下吗

**Comment by aLiang-xyl** [comment]
你们的qos设置的多少？

**Comment by tianbowen14300** [comment]
> 你们的qos设置的多少？

我这边大部分都是0 因为数据量大 使用1的话太耗费资源了 而且我这边对数据完整性要求不高

**Comment by tianbowen14300** [comment]
> 你们的qos设置的多少？

https://blog.csdn.net/lblblblblzdx/article/details/81159478

**Comment by tianbowen14300** [comment]
> 你们的qos设置的多少？

看了好多帖子都说qos改为1就可以 但是试了还是不行

**Comment by aLiang-xyl** [comment]
A客户端发送消息----->mqtt服务端----->B消费消息，这个错误是发生在A还是B

**Comment by tianbowen14300** [comment]
> A客户端发送消息----->mqtt服务端----->B消费消息，这个错误是发生在A还是B

A

**Comment by aLiang-xyl** [comment]
你们异步发送async是不是设置的true

**Comment by tianbowen14300** [comment]
> 你们异步发送async是不是设置的true

我这边设置的是true

**Comment by aLiang-xyl** [comment]
这个问题是因为async异步发送设置为true导致的。底层类似于线程池的队列，maxInflight类似于线程池队列的最大长度，如果需要发送的消息大于这个长度就会报这个错误。解决办法，方式1：设置maxInflight尽可能的设置大一些，但是还是有发生这个错误的可能；方式2：关闭异步发送，则不受maxInflight的影响。

**Comment by aLiang-xyl** [comment]
如果使用方式1，可能会导致很多消息丢失，比如服务突然崩溃，没有发送的消息就丢失了

**Comment by tianbowen14300** [comment]
> 如果使用方式1，可能会导致很多消息丢失，比如服务突然崩溃，没有发送的消息就丢失了

如果不用异步的话会有什么影响呢

**Comment by aLiang-xyl** [comment]
不用异步的话就是在你的当前线程中发送消息等待发送成功，异步的话实际上是丢到本地的待发送队列中，然后直接就返回了，这个时候消息发没发送要看队列里消息是否有积压。异步发送的话相对于你当前的接口基本上没有时间消耗，同步是有等待消息发送成功的时间消耗的。

**Comment by tianbowen14300** [comment]
> 不用异步的话就是在你的当前线程中发送消息等待发送成功，异步的话实际上是丢到本地的待发送队列中，然后直接就返回了，这个时候消息发没发送要看队列里消息是否有积压。异步发送的话相对于你当前的接口基本上没有时间消耗，同步是有等待消息发送成功的时间消耗的。

非异步的话 如果消息大量积压还是会有问题的是吧

**Comment by aLiang-xyl** [comment]
> > 不用异步的话就是在你的当前线程中发送消息等待发送成功，异步的话实际上是丢到本地的待发送队列中，然后直接就返回了，这个时候消息发没发送要看队列里消息是否有积压。异步发送的话相对于你当前的接口基本上没有时间消耗，同步是有等待消息发送成功的时间消耗的。
> 
> 非异步的话 如果消息大量积压还是会有问题的是吧

比如每秒有1000条消息，不管是同步还是异步，这个消息总量是不变的，都需要发送这1000条消息，唯一有影响的就是你的当前的接口处理的总时间，同步的话，这个时间就算在你这个接口上了。

**Comment by tianbowen14300** [comment]
> > > 不用异步的话就是在你的当前线程中发送消息等待发送成功，异步的话实际上是丢到本地的待发送队列中，然后直接就返回了，这个时候消息发没发送要看队列里消息是否有积压。异步发送的话相对于你当前的接口基本上没有时间消耗，同步是有等待消息发送成功的时间消耗的。
> > 
> > 
> > 非异步的话 如果消息大量积压还是会有问题的是吧
> 
> 比如每秒有1000条消息，不管是同步还是异步，这个消息总量是不变的，都需要发送这1000条消息，唯一有影响的就是你的当前的接口处理的总时间，同步的话，这个时间就算在你这个接口上了。

好的 我试一下

**Comment by aLiang-xyl** [comment]
怎么样，解决了吗？
